logging:
  level:
    org.apache: warn
    org.springframework: info
    hu.progmasters: debug
    org.springframework.web: warn
    org.hibernate: error
  pattern:
    console: "%cyan(%d{yyyy-MM-dd HH:mm:ss}) [%green(%thread)] %highlight(%-5level) %yellow(%logger{36}) - %msg%n"

server:
  port: 8080

cors-policies: http://192.168.0.101:4200, http://localhost:4200, http://127.0.0.1:4200

client-url: http://localhost:4200
